# Main orchestration file
# To disable a service: comment out its include line

include:
  - path: ./services/bazarr/bazarr.yml
  - path: ./services/calibre-web-automated/calibre-web-automated.yml
  - path: ./services/comics/komga.yml
  - path: ./services/flaresolverr.yml
  - path: ./services/gluetun-qbittorrent-port-manager.yml
  - path: ./services/gluetun.yml
  - path: ./services/homepage/homepage.yml
  - path: ./services/portainer/portainer.yml
  - path: ./services/prowlarr/prowlarr.yml
  - path: ./services/qbittorrent/qbittorrent.yml
  - path: ./services/radarr/radarr.yml
  - path: ./services/shelfmark/shelfmark.yml
  - path: ./services/smokeping/smokeping.yml
  - path: ./services/sonarr/sonarr.yml
  - path: ./services/tautulli/tautulli.yml
  # - path: ./services/tdarr.yml
