services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - C:\MEDIA_AUTOMATION\Bazarr/Config:/config
      - E:\media\movies:/data/movies # should match radarr movies directory
      - E:\media\tvshows:/data/tvshows # should match sonarr tv shows directory
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - arrs

networks:
  arrs:
    external: true
