services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - C:\MEDIA_AUTOMATION\Sonarr\Config:/config
      - C:\MEDIA_AUTOMATION\Sonarr\Backup:/data/Backup
      - E:\media\tvshows:/data/tvshows
      - C:\MEDIA_AUTOMATION\Downloads:/data/downloads
    restart: unless-stopped
    network_mode: service:ts-remote-access
