services:
  ts-remote-access:
    image: tailscale/tailscale:latest
    container_name: ts-remote-access
    hostname: media-server
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    ports:
      - 5055:5055 # overseerr
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 7575:7575 # homarr
    restart: unless-stopped
